name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d

      - name: Install QPM
        run: |
          wget https://github.com/QuestPackageManager/QPM.CLI/releases/latest/download/qpm-linux-x64 -O qpm
          chmod +x qpm
          sudo mv qpm /usr/local/bin/qpm

      - name: Check QPM
        run: qpm --version

      - name: QPM Restore
        run: qpm restore --verbose

      - name: Build
        run: qpm s build
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Package qmod
        run: qpm qmod zip

      - uses: actions/upload-artifact@v4
        with:
          name: NameTags.qmod
          path: "*.qmod"
          if-no-files-found: error
